function [min_mat] = find_local_min(in_mat)

center =    (in_mat(2:end-1,2:end-1)<in_mat(3:end,2:end-1)) &...
            (in_mat(2:end-1,2:end-1)<in_mat(1:end-2,2:end-1))&...
            (in_mat(2:end-1,2:end-1)<in_mat(2:end-1,3:end)) &...
            (in_mat(2:end-1,2:end-1)<in_mat(2:end-1,1:end-2)) &...
            (in_mat(2:end-1,2:end-1)<in_mat(1:end-2,1:end-2)) &...
            (in_mat(2:end-1,2:end-1)<in_mat(3:end,3:end)) &...
            (in_mat(2:end-1,2:end-1)<in_mat(3:end,1:end-2)) &...
            (in_mat(2:end-1,2:end-1)<in_mat(1:end-2,3:end))...
    ;
% Pad zeros to sides of the center matrix
full = horzcat(zeros(size(center,1),1),center,zeros(size(center,1),1));
full = vertcat(zeros(1,size(full,2)), full, zeros(1,size(full,2)));
min_mat = full;


